spring:
  devtools:
    restart:
      exclude:  static/**,public/**
      enabled:  true
  profiles:
    active: dev
swagger:
  production: false
  basic:
    enable: true
    username: root
    password: root