spring:
  devtools:
    restart:
      exclude:  static/**,public/**
      enabled:  true
  profiles:
    active: dev
swagger:
  production: false
  basic:
    enable: true
    username: root
    password: root
#md5私钥
appSecret: fc2ce7ee45ae45729932b25d6d2607b9